### ISSUE TITLE
HD video decoding issues

### ISSUE THREAD

**Issue by avafinger** [rafaello7/nano-video#1]
@rafaello7 ,
I just tried your nano-video with a MP4 sample and MKV sample.
For small win size is ok, for HD res there are some issues, like freeze at some random time. Board is still running.

Video samples: 
Some times works (HW decoding), SW (always works)
http://mirrors.standaloneinstaller.com/video-sample/jellyfish-25-mbps-hd-hevc.mp4

This always in SW but get almost 700% cpu and rendering is very slow, maybe 2 fps.
http://mirrors.standaloneinstaller.com/video-sample/jellyfish-25-mbps-hd-hevc.mkv

I am not sure is codec issues or not.

here is the log so you can check what could be the issue:

```
[ 3746.496000] alloc_contig_range: [78e00, 78f00) PFNs busy
[ 3746.496000] alloc_contig_range: [78f00, 79000) PFNs busy
[ 3746.504000] alloc_contig_range: [78e00, 78f00) PFNs busy
[ 3746.508000] alloc_contig_range: [78f00, 79000) PFNs busy
[ 3746.516000] alloc_contig_range: [79200, 79600) PFNs busy
[ 3746.520000] alloc_contig_range: [79300, 79700) PFNs busy
[ 3746.524000] alloc_contig_range: [79400, 79800) PFNs busy
[ 3746.532000] alloc_contig_range: [79500, 79900) PFNs busy
[ 3746.540000] alloc_contig_range: [79600, 79a00) PFNs busy
[ 3746.540000] alloc_contig_range: [79700, 79b00) PFNs busy
[ 3747.468000] cma: cma_alloc: alloc failed, req-size: 1377 pages, ret: -16
[ 3747.468000] nx-vpu c0080000.video-codec: nx_alloc_memory is failed
[ 3747.472000] [DRV|VPU]drivers/media/platform/nxp-vpu/nx_vpu_dec_v4l2.c(1301): Failed to allocate decoder buffers.
[ 3747.476000] [DRV|VPU]drivers/media/platform/nxp-vpu/nx_vpu_dec_v4l2.c(1424): vpu_dec_decode_slice: additional buffers register failed
[ 3747.480000] nx-vpu c0080000.video-codec: vpu_dec_decode_slice failed, err=-12
[ 3747.500000] cma: cma_alloc: alloc failed, req-size: 1530 pages, ret: -16
[ 3747.500000] nx-vpu c0080000.video-codec: nx_alloc_memory is failed
[ 3747.508000] [DRV|VPU]drivers/media/platform/nxp-vpu/nx_vpu_dec_v4l2.c(1301): Failed to allocate decoder buffers.
[ 3747.516000] [DRV|VPU]drivers/media/platform/nxp-vpu/nx_vpu_dec_v4l2.c(1424): vpu_dec_decode_slice: additional buffers register failed
[ 3747.528000] nx-vpu c0080000.video-codec: vpu_dec_decode_slice failed, err=-12
[ 3747.544000] cma: cma_alloc: alloc failed, req-size: 1530 pages, ret: -16
[ 3747.544000] nx-vpu c0080000.video-codec: nx_alloc_memory is failed
[ 3747.552000] [DRV|VPU]drivers/media/platform/nxp-vpu/nx_vpu_dec_v4l2.c(1301): Failed to allocate decoder buffers.
[ 3747.560000] [DRV|VPU]drivers/media/platform/nxp-vpu/nx_vpu_dec_v4l2.c(1424): vpu_dec_decode_slice: additional buffers register failed
[ 3747.572000] nx-vpu c0080000.video-codec: vpu_dec_decode_slice failed, err=-12
[ 3925.984000] alloc_contig_range: 803 callbacks suppressed
[ 3925.984000] alloc_contig_range: [7c000, 7c1fb) PFNs busy
[ 3925.992000] alloc_contig_range: [7c100, 7c2fb) PFNs busy
[ 3926.000000] alloc_contig_range: [7c000, 7c07f) PFNs busy
[ 3926.000000] alloc_contig_range: [7c080, 7c0ff) PFNs busy
[ 3926.008000] alloc_contig_range: [7c100, 7c17f) PFNs busy
[ 3926.012000] alloc_contig_range: [7c180, 7c1ff) PFNs busy
[ 3997.364000] alloc_contig_range: [7c000, 7c1fb) PFNs busy
[ 3997.364000] alloc_contig_range: [7c100, 7c2fb) PFNs busy
[ 3997.372000] alloc_contig_range: [7c000, 7c07f) PFNs busy
[ 3997.372000] alloc_contig_range: [7c080, 7c0ff) PFNs busy
[ 3997.380000] alloc_contig_range: [7c100, 7c17f) PFNs busy
[ 3997.384000] alloc_contig_range: [7c180, 7c1ff) PFNs busy
[ 3997.396000] alloc_contig_range: [7c500, 7cafa) PFNs busy
[ 3997.396000] alloc_contig_range: [7c600, 7cbfa) PFNs busy
[ 3997.404000] alloc_contig_range: [7c700, 7ccfa) PFNs busy
[ 3997.408000] alloc_contig_range: [7c800, 7cdfa) PFNs busy
[ 3997.448000] cma: cma_alloc: alloc failed, req-size: 1683 pages, ret: -16
[ 3997.448000] nx-vpu c0080000.video-codec: nx_alloc_memory is failed
[ 3997.456000] [DRV|VPU]drivers/media/platform/nxp-vpu/nx_vpu_dec_v4l2.c(1301): Failed to allocate decoder buffers.
[ 3997.464000] [DRV|VPU]drivers/media/platform/nxp-vpu/nx_vpu_dec_v4l2.c(1424): vpu_dec_decode_slice: additional buffers register failed
[ 3997.476000] nx-vpu c0080000.video-codec: vpu_dec_decode_slice failed, err=-12
[ 3997.484000] cma: cma_alloc: alloc failed, req-size: 1683 pages, ret: -16
[ 3997.488000] nx-vpu c0080000.video-codec: nx_alloc_memory is failed
[ 3997.492000] [DRV|VPU]drivers/media/platform/nxp-vpu/nx_vpu_dec_v4l2.c(1301): Failed to allocate decoder buffers.
[ 3997.496000] [DRV|VPU]drivers/media/platform/nxp-vpu/nx_vpu_dec_v4l2.c(1424): vpu_dec_decode_slice: additional buffers register failed
[ 3997.500000] nx-vpu c0080000.video-codec: vpu_dec_decode_slice failed, err=-12
nanopim3@nanopim3:~$ 

```

**Comment by avafinger** [comment]
You can reproduce the issues like so:

with a fresh boot:
a) Run http://mirrors.standaloneinstaller.com/video-sample/star_trails.mkv
b) Run https://github.com/bower-media-samples/big-buck-bunny-1080p-30s/ (video.mp4)

It just ran fine, check dmesg and you can see the issues are starting to occur:
```
[  143.968000] alloc_contig_range: [79a00, 79bfb) PFNs busy
[  143.972000] alloc_contig_range: [79a80, 79aff) PFNs busy

```

Run video.mp4 again and you freeze nano video, now you can see the cma and vpu memory errors.

**Comment by rafaello7** [comment]
The "PFNs busy" message is not a fatal error. It is printed at info message level. The message appears when a non-moveable page is encountered within CMA (contiguous memory allocator) area. I will try to figure out why this is happening and whether it may be avoided. I write when I will know more.

It looks the _jellyfish-25-mbps-hd-hevc.mp4_ file is encoded in h264 format, despite their name suggest _hevc_ format (_h265_?). You can check the format using _ffprobe_ program. The _h264_ format is supported by VPU hardware. Second file, _jellyfish-25-mbps-hd-hevc.mkv_ is really encoded in _hevc_ format, which is not supported by VPU. In this case _GStreamer_ attempts to decode it by software, hence the high cpu usage and miserable result.

You can increase amount of memory reserved for CMA area using kernel parameter _cma=.._. By default 96MB is reserved. I think it would be enough when the non-moveable pages would be not allocated within the area. Try with 128MB, _cma=128m_.

**Comment by avafinger** [comment]
i have cma=80m for AW platform, i think 96m should be enough for H264 (HW), maybe if SW more is needed.
But, have you noticed **star_trails.mkv** and **video.mp4** are both H264? Could you fire both in that respective order and reproduce the problem? 
Anyway if cma=128m fix that(for HW)  it is not an issue, will check that.

**Comment by rafaello7** [comment]
It looks the CMA memory allocator in kernel was not sufficiently thought out. I try to prepare a fix which should improve the situation and give you for testing.

**Comment by rafaello7** [comment]
Please test with [this kernel](https://drive.google.com/open?id=0B8m_JgFBfEzwclNFLWpGSWNlZW8).

It looks 96MB of memory may be not enough. I have increased default cma size to 128 MB.

**Comment by avafinger** [comment]
@rafaello7 ,
cma=128 has fixed the errors. Thanks.

I wonder if you have some code experiments to expose encoding/decoding in C without gstreamer?
Do you plan on adding mali (libdrm also) and work with xf86-video-armsoc?

**Comment by rafaello7** [comment]
I have added also a correction for problem which lead to the "PFNs busy" message. But despite the correction sometimes allocation did fail when cma was 96 MB. BTW the CMA memory is not excluded from usual allocations. It may be used when other memory is exhausted.

The VPU encoder and decoder are available as video4linux devices. But the VPU decoder performs only small piece of work. Hence I used GStreamer which does the rest. I was looking for programs that could use such kind of hardware decoding, but I found only GStreamer. Samsung Artik platform uses also GStreamer.

As of mali, I have ported the driver to 4.11 kernel but it is not built by default. The Mali driver needs also some userland library (libMali.so) which would make use of the driver. I was unable to find any such library that would work.

**Comment by avafinger** [comment]
I was thinking about ffmpeg which can be used for some tasks and it is possible to pipe output to say mvp or others.
Have you checked if odroid would have some mali stack, using that could raise some  license issues but it is just for minor experiments. I have not followed them for some time, so i am not up to date with mali version in use there and development.

I am closing this, if i find something wrong i re-open or post here.

**Comment by rafaello7** [comment]
I checked Mali library for Odroid-C2 (I have this board, too) but it does not work with NanoPi.  I also looked at Artik repositories but I didn't found Mali libraries there. Since FriendlyARM will release 64-bit system soon, as mentioned by awl on "Bump.." thread, maybe also the library will be available. It will come out.

Ffmpeg was used by me for testing. It was used for extracting h264 stream. I created program which feeds decoder with the stream and displays decoded video output. This works, although I would not call it a video program. To play video, the output must be clocked with appropriate speed, synchronized with audio. Also, user can give files in various formats, my program handled only h264 video stream with one, hard-coded video size. Much work would be needed to create ready program than with GStreamer. Actually the nano-video program is created for reference. It lacks many of features.

**Comment by avafinger** [comment]
I know what you mean. I just wondered if you had the basics to encode and decode for each frame. This samsung way of dealing with the engine is kind of unique (for me), so i just wanted some thing not linked to gstreamer or C++ for easy learning, 
Anyways, Let's wait for FE release, but they don't have a time frame so it could be tomorrow or next year, who knows. Thanks for your work.
